
services:
  seed_node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seed_node
    ports:
      - "3000:8080"  # API HTTP
      - "4000:8081"  # WebSocket
    environment:
      - NODE_ENV=production
      - HTTP_PORT=8080
      - WS_PORT=8081
      - SEED_NODES=  # No hay SEED_NODES porque es el nodo inicial
    networks:
      - p2p_network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

networks:
  p2p_network:
    name: p2p_network
    driver: bridge
